name = "pacmacmobile-cloudflare"
type = "javascript"
account_id = "your-cloudflare-account-id"
workers_dev = true
compatibility_date = "2024-05-01"

[build]
command = "npm install && npm run build"
cwd = "public"

[vars]
SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_ANON_KEY = "your_anon_key"
OPENAI_API_KEY = "your_openai_key"
CLOUDFLARE_API_TOKEN = "your_cloudflare_token"
CLOUDFLARE_ZONE_ID = "your_zone_id"
ROOT_DOMAIN = "pacmacmobile.com"
DYNADOT_API_KEY = "your_dynadot_key"
STRIPE_SECRET_KEY = "sk_test_..."
PUBLIC_URL = "https://pacmacmobile.pages.dev"
