services:
  - type: web
    name: pacmacmobile-resume
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_ZONE_ID
        sync: false
      - key: ROOT_DOMAIN
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: DYNADOT_API_KEY
        sync: false
